### ISSUE TITLE
Bugs for editable table

### ISSUE THREAD

**Issue by emibanana** [BeverCRM/PCF-EditableTable#19] opened 2023-06-10 15:00 UTC
Sometimes the pup up warning menu is hidden behind the grid, which makes it unusable. See attached video
If a record has a restriction for deletion because it has related child relationship that set to restrict deletion, the editable table will not give an error message like the out-of-the-box control do, it will simply assume it’s deleted successfully, but when you refresh it, it will come back again.
 
Here are some bugs that I have found:

 

1, Sometimes the pup up warning menu is hidden behind the grid, which makes it unusable.

![image003](https://github.com/BeverCRM/PCF-EditableTable/assets/120373920/d7d13de9-3a48-4fb9-aff2-795657b5c54e)

2, If a record has a restriction for deletion because it has related child relationship that set to restrict deletion, the editable table will not give an error message like the out-of-the-box control do, it will simply assume it’s deleted successfully, but when you refresh it, it will come back again.

And here are some suggestions for improvements:

 
![image001](https://github.com/BeverCRM/PCF-EditableTable/assets/120373920/bdd7def8-34ea-4bbd-a14b-c6041be6e459)

If The horizontal slider can appear always as a top element rather than placed at the bottom of the row, it will improve the experience significantly, so that user wont scroll down to the bottom to use the horizontal slider, see below pictures

![image002](https://github.com/BeverCRM/PCF-EditableTable/assets/120373920/c888cdad-0b50-4206-8f5d-1500770ce213)

If you can allow only double clicking a certain area to go into the form of that row, rather than anywhere, that would improve the usage as well, as currently it gets very easy to go into the form view.
Some fields are set as read only field, such as powerfx calculated column, or ready only field set by the table; they are editable in the editable table control, but will give an error when you try to save them. See below warning (which also shows bug no.1). If you can lock read only field that would be awesome!

**Comment by RubenAghajanyan** [comment] 2023-06-12 07:27
Hi @emibanana,

Thanks for the information.

Bug 1: Can you please share more information (or maybe a recorded video), under which conditions it happens? We need to be able to reproduce.

Bug 2: We will fix it and let you know.

Improvements: Thanks for the suggestions. We will consider them with the new version and let you know.

**Comment by emibanana** [comment] 2023-06-12 10:58
Hi @RubenAghajanyan 

See below video, this was recorded on version 1.0, about few weeks ago.

https://github.com/BeverCRM/PCF-EditableTable/assets/120373920/8a1c67d7-53e8-4ecd-810f-1a8459148248


https://github.com/BeverCRM/PCF-EditableTable/assets/120373920/d39e2431-b585-48fb-a37a-5bb037a252a6

**Comment by emibanana** [comment] 2023-06-26 01:02
> Hi @emibanana,
> 
> Thanks for the information.
> 
> Bug 1: Can you please share more information (or maybe a recorded video), under which conditions it happens? We need to be able to reproduce.
> 
> Bug 2: We will fix it and let you know.
> 
> Improvements: Thanks for the suggestions. We will consider them with the new version and let you know.

Hi, would there be any ETA for this fix? I really love this control! :D

**Comment by emibanana** [comment] 2023-06-26 01:02
> Hi @emibanana,
> 
> Thanks for the information.
> 
> Bug 1: Can you please share more information (or maybe a recorded video), under which conditions it happens? We need to be able to reproduce.
> 
> Bug 2: We will fix it and let you know.
> 
> Improvements: Thanks for the suggestions. We will consider them with the new version and let you know.

Hi, would there be any ETA for this fix? I really love this control! :D

**Comment by RubenAghajanyan** [comment] 2023-07-04 10:26
@emibanana,

Regarding your 1st enhancement. Instead of scrolling down (to find a horizontal scroll), you can just select one row at the top and use keyboards left-arrow or right-arrow. See the video below.

![editableTable](https://github.com/BeverCRM/PCF-EditableTable/assets/10652791/10bb2f59-2a28-4791-986f-f8954d818e91)

We're checking other bugs & enhancements. Will keep you updated.

**Comment by emibanana** [comment] 2023-07-04 10:31
> @emibanana,
> 
> Regarding your 1st enhancement. Instead of scrolling down (to find a horizontal scroll), you can just select one row at the top and use keyboards left-arrow or right-arrow. See the video below.
> 
> ![editableTable](https://user-images.githubusercontent.com/10652791/250868946-10bb2f59-2a28-4791-986f-f8954d818e91.gif)
> 
> We're checking other bugs & enhancements. Will keep you updated.

Yes you are right I just learnt that after I submitted, this was a out of box grid behaviour too. Also the out of box power Apps grid view also allows you to specify the total number of rows to show, which essentially defines the total height of the grid control. If I set it to 10-15, and allow auto adjustment based on available space, it will achieve what I want. I believe your pcf control can do that as well, either already implemented or not yet, I haven't tested it

**Comment by RubenAghajanyan** [comment] 2023-07-04 10:33
yes, PCF will do the same. You can adjust row count, similar as in the standard Dynamics 365 grid.

**Comment by emibanana** [comment] 2023-07-04 10:36
Yes thanks! Sorry just want to add more, not just arrow keys can let you scroll let or right, you can press shift and mouse scroll wheel to scroll left or right, which is the best method I believe as you barely need to move your hand

**Comment by RubenAghajanyan** [comment] 2023-10-09 08:30
@emibanana 

The following issues are fixed.

1. _Sometimes the pop-up warning menu is hidden behind the grid, which makes it unusable._
This issue is fixed now. 

2.  _If a record has a restriction for deletion because it has a related child relationship that is set to restrict deletion, the editable table will not give an error message like the out-of-the-box control does, it will simply assume it’s deleted successfully, but when you refresh it, it will come back again._ 
The issue is fixed. If there is any restriction for deletion, you will receive an error popup, and the records will remain in the table without the need to refresh. 

3. _If The horizontal slider can appear always as a top element rather than placed at the bottom of the row, it will improve the experience significantly, so that the user won't scroll down to the bottom to use the horizontal slider, see below pictures_
This enhancement is now available. The horizontal slider will always be visible as a top element. Additionally, the header where the buttons are located, will also be visible as a top element, so that the user doesn't have to scroll up to save the changes. 

4. _Some fields are set as read-only, such as powerfx calculated column, or ready-only field set by the table; they are editable in the editable table control but will give an error when you try to save them._ 
Calculated and rollup fields are read only now.


_If you can allow only double-clicking a certain area to go into the form of that row, rather than anywhere_ - this one is not planned yet to be implemented, but we will consider it in future releases.

Closing this bug. If you'll have further issues please open a new bug.

**Closed by RubenAghajanyan** 2023-10-09 08:30 UTC
Labels: bug, enhancement
